# Generated by Django 5.2 on 2025-05-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
