# Generated by Django 5.2 on 2025-05-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SMSapp', '0002_delete_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.TextField(max_length=9)),
                ('name', models.TextField(max_length=100)),
                ('contact', models.IntegerField(max_length=11)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
