# Generated by Django 5.2 on 2025-05-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0008_alter_attendance_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('result', models.CharField(max_length=10)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMSapp.attendance')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SMSapp.student')),
            ],
        ),
    ]
