# Generated by Django 5.2 on 2025-05-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0009_grouping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouping',
            name='attendance',
        ),
    ]
