# Generated by Django 5.2.1 on 2025-05-20 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0011_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SMSapp.subject'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='excused_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject')},
        ),
    ]
