# Generated by Django 5.2.1 on 2025-05-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0014_student_gwa_delete_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dropout_risk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='performance_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
