# Generated by Django 5.2.1 on 2025-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0015_student_dropout_risk_student_performance_summary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='performance_summary',
            new_name='performance_analysis',
        ),
        migrations.AddField(
            model_name='student',
            name='performance_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
