# Generated by Django 5.2.1 on 2025-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0017_student_dropout_risk_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='performance_insights',
            field=models.TextField(blank=True, null=True),
        ),
    ]
